### ISSUE TITLE
Import Error in boilerpipe python 2.7 . JVM isn't starting

### ISSUE THREAD

**Issue by ethan-hunt-007** [misja/python-boilerpipe#34]
My JAVA PATH is correct and all packages regarding boilerpipe is installed but still can't understand the issue. Here is the error:

> > > import boilerpipe

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import boilerpipe
  File "C:\Python27\lib\site-packages\boilerpipe__init__.py", line 10, in <module>
    jpype.startJVM(jpype.getDefaultJVMPath(), "-Djava.class.path=%s" % os.pathsep.join(jars))
  File "C:\Python27\Lib\site-packages\JPype1-0.6.0-py2.7-win32.egg\jpype_core.py", line 50, in startJVM
    _jpype.startup(jvm, tuple(args), True)
RuntimeError: Unknown Exception

**Comment by abhigenie92** [comment]
same issue!

**Comment by tuxdna** [comment]
@ethan-hunt-007 @abhigenie92 Does it still happen ?

**Comment by tuxdna** [comment]
Closing the issue as no updates provided, and it seems to work in current versions.
