### ISSUE TITLE
"not a gzip file" error

### ISSUE THREAD

**Issue by shrshore** [misja/python-boilerpipe#48]
I'm just obtaining a ReadError when I install this package through pip. Anyone can help? Thanks!
```
$ pip install -r requirements.txt
Collecting JPype1 (from -r requirements.txt (line 1))
  Downloading JPype1-0.6.2.tar.gz (147kB)
    100% |████████████████████████████████| 153kB 1.1MB/s 
Collecting chardet (from -r requirements.txt (line 2))
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Building wheels for collected packages: JPype1
  Running setup.py bdist_wheel for JPype1 ... done
  Stored in directory: 
Successfully built JPype1
Installing collected packages: JPype1, chardet
Successfully installed JPype1-0.6.2 chardet-3.0.4
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    download_jars(datapath=DATAPATH)
  File "setup.py", line 20, in download_jars
    tar = tarfile.open(tgz_name, mode='r:gz')
  File "/users/pxie1/miniconda2/lib/python2.7/tarfile.py", line 1693, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/users/pxie1/miniconda2/lib/python2.7/tarfile.py", line 1751, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
```
I wonder how to fix it. I try to install some other python packages like ``tqdm`` and it run smoothly.

**Comment by bennokr** [comment]
I believe the file that it should download has moved to https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/boilerpipe/boilerpipe-1.2.0-bin.tar.gz . I was successful installing from source, after downloading that file in the source directory.
